name: build and push to github package registry

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
    - name: pack for nuget
      run: dotnet pack -c Release -o out Microsoft.Identity.Web prerel Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
    - name: Publish nuget to github registry
      run: dotnet nuget push Microsoft.Identity.Web/bin/Release/*.nupkg -s https://nuget.pkg.github.com/jpda/index.json -k ${GITHUB_TOKEN}  
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
