name: build and push to github package registry

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
    - name: pack for nuget
      run: dotnet pack -c Release Microsoft.Identity.Web/Microsoft.Identity.Web.csproj
    - name: Setup nuget config
      run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .nuget.config > nuget.config
    - name: Publish nuget
      run: dotnet nuget push Microsoft.Identity.Web/bin/Release/*.nupkg -s "github"
