name: build and push to github package registry

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: cd Microsoft.Identity.Web && dotnet build --configuration Release
    - name: Setup nuget config
      run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .nuget.config > nuget.config
    - name: pack for nuget
      run: dotnet pack -c Release -o out Microsoft.Identity.Web prerel
    - name: Publish nuget to github registry
      run: dotnet nuget push src/bin/Release/*.nupkg -s "github"
